# Generated by Django 3.2.9 on 2021-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='Unknown', max_length=200000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
