# Generated by Django 3.2.9 on 2021-12-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211201_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='delivery_time',
        ),
    ]
